# Generated by Django 4.2 on 2024-08-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_items_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='items_price',
            new_name='item_price',
        ),
    ]
